language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t maracartman/react-test -f ./fe-products-searcher-ml/Dockerfile.dev ./fe-products-searcher-ml
  - docker build -t maracartman/express-test -f ./be-products-searcher-ml/Dockerfile.dev ./be-products-searcher-ml

script:
  - docker run -e CI=true maracartman/react-test npm run test:nowatch -- --coverage
  - docker run -e CI=true maracartman/express-test npm run test

after_success:
  - docker build -t maracartman/ml-client ./fe-products-searcher-ml
  - docker build -t maracartman/ml-nginx ./nginx
  - docker build -t maracartman/ml-server ./be-products-searcher-ml
  # Log In into Docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker hub
  - docker push maracartman/ml-client
  - docker push maracartman/ml-nginx
  - docker push maracartman/ml-server
deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: ml-searcher-cl
  env: MlSearcherCl-env
  bucket_name: elasticbeanstalk-us-west-1-768964238245
  bucket_path: ml-searcher
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY